apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: hpc-virt-manager
  labels:
    app: hpc-virt-manager
    hpc-virt-manager.io/version: 1.0.0
    hpc-virt-manager.io/managed: "true"
data:
  basicauth.conf: |
    auth_basic "Restricted Content";
    auth_basic_user_file /etc/nginx/secret.d/.htpasswd;
