apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: hpc-virt-manager
  labels:
    app: hpc-virt-manager
    hpc-virt-manager.io/version: 1.0.0
    hpc-virt-manager.io/managed: "true"
data:
  .htpasswd: YWRtaW46JGFwcjEkMk53ckdFZVkkZmtPZkZldVR4Rm5pZzBsc2NaV3c1MQo=
